# Generated by Django 4.0.2 on 2022-04-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('company_logo', models.ImageField(blank=True, upload_to='company logo')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('duration', models.SmallIntegerField()),
                ('per_person_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel_name', models.CharField(max_length=45)),
                ('bus_name', models.CharField(max_length=45)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('user_type', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile picture')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.package')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goheen.traveller')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('house_no', models.SmallIntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people', models.SmallIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.package')),
                ('traveller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goheen.traveller')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog picture')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goheen.traveller'),
        ),
        migrations.CreateModel(
            name='AgencyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('user_type', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile picture')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goheen.agency')),
            ],
        ),
    ]
