# Generated by Django 4.0.2 on 2022-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goheen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencymember',
            name='user_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='user_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
