# Generated by Django 4.0.2 on 2022-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goheen', '0003_alter_agencymember_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='user_type',
            field=models.CharField(default='Traveller', editable=False, max_length=10),
        ),
    ]
