# Generated by Django 4.0.2 on 2022-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goheen', '0004_alter_traveller_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencymember',
            name='user_type',
            field=models.CharField(default='agency_member', max_length=30),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='user_type',
            field=models.CharField(default='Traveller', max_length=10),
        ),
    ]
