# Generated by Django 4.0.2 on 2022-04-10 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goheen', '0005_alter_agencymember_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
