# Generated by Django 4.0.2 on 2022-04-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goheen', '0006_traveller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencymember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agencymember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agencymember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='last_name',
        ),
        migrations.AddField(
            model_name='agencymember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
