# Generated by Django 4.0.2 on 2022-04-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goheen', '0007_remove_agencymember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goheen.blog'),
        ),
    ]
