# Generated by Django 4.0.2 on 2022-04-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goheen', '0009_alter_blogimages_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='traveller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goheen.traveller'),
        ),
    ]
